### ISSUE TITLE
Obtain valid JWT Token through CLI

### ISSUE THREAD

**Issue by jmtts** [werk24/werk24-python#14]
**Is your feature request related to a problem? Please describe.**
For debugging purposes it is sometimes very helpful to quickly obtain a valid JWT token, so that we can download the payload_bytes manually / semi-automated. 

**Describe the solution you'd like**
Ideally, I would like to get the JWT token with a CLI call similar to
```w24cli authentication --ask-jwt-token```

**Describe alternatives you've considered**
The alternative of printing the JWT token to the command line with every request seems to be dangerous. The information might end up in a log file.

**Comment by werk24** [comment]
Closed by #15
